### ISSUE TITLE
Video quality.

### ISSUE THREAD

**Issue by steam3d** [LavamasterYT/AirPods-for-Windows#2]
I want to improve video quality. I made a new video file but it is grayish. How do you fix this?
![image](https://user-images.githubusercontent.com/30986874/71646469-2d333c00-2cfa-11ea-9086-76ef122c1cb3.png)

**Comment by LavamasterYT** [comment]
Alright so the way I did mine is I got the raw video from the OS, and since it had some sort of green screen effect going on, I just replaced it with white from the background and it worked. If this doesn't make sense, you can send me the video file you are using and I can try to make it work for you.

**Comment by steam3d** [comment]
I found out, i must convert a video's color space to `bt709`. Then white color will be white, not grayish.
