### ISSUE TITLE
You must be on Windows Version 1903

### ISSUE THREAD

**Issue by maxgrass** [LavamasterYT/AirPods-for-Windows#5]
Only error popup:
> - Service.exe
> - Configuration > Add/Remove from Startup

> Start/Stop Service:
![image](https://user-images.githubusercontent.com/169885/85024122-f05ae480-b175-11ea-88ef-0da552507c7a.png)

![image](https://user-images.githubusercontent.com/169885/85023936-a4a83b00-b175-11ea-84c6-f32f4b3b5ec0.png)

**Comment by LavamasterYT** [comment]
I found out the issue, in the code, I checked for 1904 instead of 1903, however the code on github is not the latest version, and I lost the source code for the latest version. So you only really have 2 solutions, 1. Update windows to the latest version or 2. Manually edit the registry entry where the build is stored. If you need help on the second options, tell me.

**Comment by LavamasterYT** [comment]
Scratch what I said, well if u want to fix it, do one of those 2 options but after some investigating, I could recover the source and push a new version.

**Comment by LavamasterYT** [comment]
It will be fixed in a later release, ETA somewhere between 1 week or less hopefully.
